apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedido
  labels:
    app: api-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pedido
  template:
    metadata:
      labels:
        app: api-pedido
    spec:
      containers:
        - name: app
#          image: pedido-api:latest
#          imagePullPolicy: IfNotPresent
          image: 084477714284.dkr.ecr.us-east-1.amazonaws.com/pedido-api-repository
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://terraform-2024031923023447980000000d.c36c48ce06uv.us-east-1.rds.amazonaws.com:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: api-pedido
  labels:
    app: api-pedido
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: api-pedido
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-pedido-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pedido
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80